### ISSUE TITLE
decode problem

### ISSUE THREAD

**Issue by sdcuike** [snowplow/referer-parser#103]
refererUrl = "http://www.baidu.com/baidu?wd=%CB%AB%C9%AB%C7%F2qq%C8%BA&tn=monline_dg";
		pageUrl = "http://www.aicai.com";
		referer = parser.parse(refererUrl, pageUrl);
		System.out.println(referer.source);
		System.out.println(referer.term);
		System.out.println("=============");

		System.out.println(URLDecoder.decode("%CB%AB%C9%AB%C7%F2qq%C8%BA", "gbk"));

////
but :

Baidu
˫ɫ��qqȺ
=============
双色球qq群
the decode problem ,how can make sure the encoding

**Comment by alexanderdean** [comment]
Convert your refererUri String into a valid java.net.URL then use this method:

https://github.com/snowplow/referer-parser/blob/master/java-scala/src/main/java/com/snowplowanalytics/refererparser/Parser.java#L110
Closing as not a referer-parser problem.
