### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by marstonstudio** [snowplow/referer-parser#153]
Please compile and release a scala 2.12 version available through maven coordinates

        <dependency>
            <groupId>com.snowplowanalytics</groupId>
            <artifactId>referer-parser_2.12</artifactId>
        </dependency>

**Comment by BenFradet** [comment]
Not yet no, we want to get some other stuff in / clean some stuff out before cutting a release which will be on central.

**Comment by travisbrown-stripe** [comment]
@BenFradet Excellent, thanks! Any idea of a timeline?

**Comment by BenFradet** [comment]
This is in our next 2-week sprint :+1:

**Comment by snadorp** [comment]
@BenFradet Any chance to push this onto the maven server soon?

**Comment by snadorp** [comment]
It only shows the `scala-referer-parser` one, not the one from this repo.

**Comment by BenFradet** [comment]
yes this repo is meant to only contain the reference data in https://github.com/snowplow-referer-parser/referer-parser/tree/develop/resources, we just haven't had the time to do the cleanup

**Comment by snadorp** [comment]
Ok, but this doesn't solve the deployment of the 2.12 version. As the `scala-referer-parser` is not a drop in replacement for this library. I would grately appreciate if you'd release the 2.12 version of this lib.

**Comment by BenFradet** [comment]
It is meant to be a drop-in replacement, scala code in this repo will be not be maintained anymore and will soon be removed.
