### ISSUE TITLE
Erlang port available

### ISSUE THREAD

**Issue by silviucpp** [snowplow/referer-parser#157]
Hello guys,

I implemented an erlang port : https://github.com/silviucpp/refererparser

Let me know if you want to add it in your readme. I can send a pull request

Silviu

**Comment by alexanderdean** [comment]
Awesome work - yes please open a PR for the README!

**Comment by silviucpp** [comment]
Done: https://github.com/snowplow/referer-parser/pull/158

**Comment by alexanderdean** [comment]
Thanks, closing this one!
