### ISSUE TITLE
phar version?

### ISSUE THREAD

**Issue by morrow95** [snowplow/referer-parser#83]
Can someone with time create a phar version or do a pull request of one using box?  This is above my head, but I cannot use without having a phar... would be extremely grateful if anyone has the time.

http://box-project.org/

**Comment by morrow95** [comment]
Requesting the phar version again @lstrojny  Really want to incorporate this in a project, but as I've said before I do not have the means to use composer and anything I have found to create a phar version requires composer to create it.

**Comment by morrow95** [comment]
+1

**Comment by lstrojny** [comment]
Duplicate of #78
